### ISSUE TITLE
Login is not possible.

### ISSUE THREAD

**Issue by WhyNotHugo** [jeffkowalski/geeknote#106]
I'm trying to log in, and I'm prompted for a developer token:

```
# geeknote login
OAuth token request failed
If you have an Evernote developer token, enter it here:
```

But this is [no longer possible](https://www.evernote.com/api/DeveloperToken.action) ("the creation of developer tokens is temporarily disabled.").

Is there something that can be done to obtain an OAuth token instead? (It prints that right away when logging in, and doesn't prompt me to visit any URL or anything alike).

**Comment by WhyNotHugo** [comment]
Could this be related to #89? Is the API key still unchanged since that report?

Is it possible for users to just plug in their own API keys?

**Comment by jeffkowalski** [comment]
Correct, the root of this issue is #89.
The proper solution will be the correct implementation of OAuth2 authentication.
In the meantime, you might petition Evernote for a developer token.
