### ISSUE TITLE
i am trying to use a web scraper

### ISSUE THREAD

**Issue by ashimonye** [jeffkowalski/geeknote#115]
UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 6 of the file C:/Users/Gideon/PycharmProjects/Youtube/weblearn.py. To get rid of this warning, pass the additional argument 'features="html.parser"' to the BeautifulSoup constructor.

  soup = bs4.BeautifulSoup(page.text)
Traceback (most recent call last):
  File "C:/Users/Gideon/PycharmProjects/Youtube/weblearn.py", line 9, in <module>
    requests.append(movie)
AttributeError: module 'requests' has no attribute 'append'

**Comment by jeffkowalski** [comment]
I'm sorry but this is report is not useful without clearly indicating steps
to reproduce the error, and an indication of what you were expecting to
happen. As well, please describe the version of geeknote and the operating
system you're using.
