### ISSUE TITLE
`show` do not find 'xxx' if title is xxx.yyy

### ISSUE THREAD

**Issue by vitaly-zdanevich** [jeffkowalski/geeknote#119]
For me this is a regression - as I remember in the past I was able to `show` note with title as `mozilla.org` by `mozilla`.

**Comment by jeffkowalski** [comment]
In order to find a term with an embedded '.' using a partial match, you should append a '*' at the end.  In your example, ```geeknote show "xxx*"``` returns the expected note.

The evernote webclient may be what you were remembering in the past.  It automatically appends "*" to search queries typed into the query box.
