### ISSUE TITLE
Every run: The soupsieve package is not installed. CSS selectors cannot be used.

### ISSUE THREAD

**Issue by Forceflow** [jeffkowalski/geeknote#123]
Installed on Ubuntu 19.10 using the instructions from the Readme. On run of every tool (geeknote, gnsync), I get this warning:

```
/usr/local/lib/python2.7/dist-packages/bs4/element.py:16: UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.
  'The soupsieve package is not installed. CSS selectors cannot be used.'
```

Both beautifulsoup4 and soupsieve are installed for Python 2.7.

(Geeknote itself seems to be functioning fine though, I use it mainly for a simple gnsync --all --download backup dump)

**Comment by jeffkowalski** [comment]
What version of geeknote are you using?
What command did you use to install it?
What happens if you uninstall bs4 and reinstall it?
Geeknote doesn't directly call for soupsieve.

**Comment by Forceflow** [comment]
Sorry, my initial report was light on the details ;)

- 2.0.19
- Downloaded and installed from source as per Readme instructions, on Ubuntu 19.10
- Reinstalling bs4 does not make any difference

**Comment by agent-kimbley** [comment]
Same problem with soupsieve,But I figure out what's going on.When I installing follow install guide with newest commit,That install error will show up,Say some like "soupsieve need python > 3.5".

**Comment by agent-kimbley** [comment]
sudo apt-get install bs4
That is solution to avoid install error with soupsieve.
