### ISSUE TITLE
No wildcard for --resource

### ISSUE THREAD

**Issue by vitaly-zdanevich** [jeffkowalski/geeknote#124]
I tried
`geeknote create --title 'My photos' --resource ~/Desktop/*.jpg`

But looks like this is not possible - only explicit names.

**Comment by jeffkowalski** [comment]
Yes, that's correct behavior, believe it or not.  It's true for any program.
The shell you're using (maybe bash or an equivalent) will expand the '*.jpg' wildcard via globbing before passing the commandline to geeknote.  Geeknote never sees the '*'.  Instead it receives something like;
```geeknote create --title 'My photos' --resource /home/vitaly/Desktop/pic1.jpg /home/vitaly/Desktop/pic2.jpg /home/vitaly/Desktop/pic3.jpg```

You could use backquotes to give each of the jpg's their own --resource flag.
```geeknote create --title 'My photos' `for f in *.jpg  ; do echo -n " --resource \"$f\"" ; done` ```
