### ISSUE TITLE
Adding to Gentoo repository

### ISSUE THREAD

**Issue by vitaly-zdanevich** [jeffkowalski/geeknote#127]
Good day, I am trying to add Geeknote into Gentoo repository, and for `ebuild` I need to set a LICENSE field - please add some open license to this repository.

**Comment by vitaly-zdanevich** [comment]
About dependencies: in Gentoo repository they miss a few, just asking, for the sake of simplicity - is it possible to drop `pysqlite`? As I understand `pysqlite` used by `sqlalchemy` for [storage.py](https://github.com/jeffkowalski/geeknote/blob/master/geeknote/storage.py).

[Here](https://github.com/sqlalchemy/sqlalchemy/blob/a6ba1662565c5e63e8a63a4020c594fa6f97befb/lib/sqlalchemy/dialects/sqlite/pysqlite.py#L15) I see that `Note that pysqlite is the same driver as the sqlite3
    module included with the Python distribution.`

**Comment by jeffkowalski** [comment]
Hi @vitaly-zdanevich, I'm adding a COPYING file to the root, which contains the text of the "GNU General Public License v3.0".  Your license field in your ebuild file should be "gpl-3.0".
As well, I'm removing the pysqlite requirement, per your recommendation.
