### ISSUE TITLE
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

### ISSUE THREAD

**Issue by pravsripad** [jeffkowalski/geeknote#16]
Same issue as that described in https://github.com/VitaliyRodnenko/geeknote/issues/328, 

I tried using the using the workaround but it does not work after two factor authentication, any suggestions? 
```
+        import ssl
+        context = ssl._create_unverified_context()
+        conn = httplib.HTTPSConnection(url, context=context)
```
Thank you.

**Comment by jeffkowalski** [comment]
Not reproducible in v2.0.1
If still a bug, please list steps to reproduce, including installation and invocation.
As well, please list locations of geeknote (e.g. ```find -name /usr ~/ -name geeknote\*```)
