### ISSUE TITLE
Is it safe to assume this is now the active geeknote project?

### ISSUE THREAD

**Issue by silviuvulcan** [jeffkowalski/geeknote#18]
I took a quick glance between https://github.com/VitaliyRodnenko/geeknote and https://github.com/jeffkowalski/geeknote Is it safe to asume that Vitaliy Rodnenko abadoned development and this is the project to follow and contribute or are you planing on merging back eventually?

Cheers & Thanks

**Comment by jeffkowalski** [comment]
I can't state Vitaliy's intentions, but he hasn't been active in months nor
responsive to pull requests.  I would be happy if he pulled my branch back
to his, but I'm not waiting.  I'm moving forward with some development and
servicing pull requests made by others.  Feel free to use my repo and to
contribute.  I'll try to be responsive.
You'll note that my repo has Travis builds turned on, so please try to get
your pull request working in automated build before issuing a pull request.

I'm unlikely to pull a request from a commit that fails to build.
Jeff

**Comment by silviuvulcan** [comment]
Fair enough, Thanks this clears it up for me.

Cheers,
Silviu
