### ISSUE TITLE
If I have installed original Geeknote - how can I switch to your?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [jeffkowalski/geeknote#20]
Please mention this at readme

**Comment by jeffkowalski** [comment]
Simply installing over-top should work.

Alternatively, you might find and remove geeknote from 
```/usr/local/lib/python*/dist-packages/geeknote*```
```/usr/local/bin/geeknote```
```/usr/local/bin/gnsync```
and 
```~/.local/lib/python*/dist-packages/geeknote*```
```~/.local/bin/geeknote```
```~/.local/bin/gnsync```
