### ISSUE TITLE
sudo pip install: You must give at least one requirement to install (see "pip help install")

### ISSUE THREAD

**Issue by vitaly-zdanevich** [jeffkowalski/geeknote#32]

**Comment by jeffkowalski** [comment]
Not sure where you're seeing that instruction.
Did you mean to say ```sudo pip install .```?  (Note the dot at the end)

**Comment by jeffkowalski** [comment]
Not reproducible in v2.0.1
Please seen clarification above (about the final "dot" needed at the end of ```pip install .```)
If still an issue, please feel free to comment and I'll re-open the issue.
