### ISSUE TITLE
TypeError: cannot concatenate 'str' and 'int' objects

### ISSUE THREAD

**Issue by vitaly-zdanevich** [jeffkowalski/geeknote#35]
`geeknote dedup --search replace --tags vi`

Connect to Evernote...Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/geeknote/geeknote.py", line 1214, in main
    Notes().dedup(**ARGS)
  File "/usr/local/lib/python2.7/dist-packages/geeknote/geeknote.py", line 1053, in dedup
    + " of " + count + ")")

**Comment by jeffkowalski** [comment]
No longer reproducible in v2.0.1
Note that the syntax for your example command is now changed.  If you want to try again in the latest version, please use 
```geeknote dedup --search replace --tag vi```
The "tags" parameter is now "tag" and can be used multiple times to specify more than one tag.
