### ISSUE TITLE
EDAMUserException(errorCode=11, parameter='Attribute "class" must be declared for element type "div".')

### ISSUE THREAD

**Issue by MikeDacre** [jeffkowalski/geeknote#39]
When creating a note in vim with the command `geeknote create --notebook Inbox --title test --content WRITE`

The following markdown: 

``````
hi

```python
import os
```
``````

Turns into the following `inputData argument` to `self.getEvernote().createNote`:

```
{'title': 'test', 'created': None, 'content': '<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE en-note SYSTEM "http://xml.evernote.com/pub/enml2.dtd">\n<en-note><p>hi</p>\n<div class="codehilite"><pre><span></span><code><span class="kn">import</span> <span class="nn">os</span>\n</code></pre></div>\n</en-note>', 'notebook': 'f34526b0-c731-4bc2-a81b-c572448d7856', 'resources': None, 'reminder': None, 'tags': None}
```

But that results in the error:

```
Connect to Evernote...EDAMUserException(errorCode=11, parameter='Attribute "class" must be declared for element type "div".')
```

I am running geeknote on Mac OS 10.9.5 with python 2.7.5, originally installed with homebrew and then forked and installed with `python2 ./setup.py install`, with the same results.

This seems to be an issue with the evernote SDK (I have version 1.25.1 installed for python2), but I am not sure how to resolve it.

This is only an issue if fenced-code-blocks is used.

**Comment by MikeDacre** [comment]
From reading the evernote documentation [here](https://dev.evernote.com/doc/articles/enml.php#prohibited), it seems that class elements are not allowed in html attributes, so I am confused by how any one uses fenced code blocks... is it just that syntax highlighting is impossible but otherwise it works fine?

**Comment by graceman9** [comment]
Same here, Ubuntu 15.10, any updates?

**Comment by jeffkowalski** [comment]
I don't see those results.  I'm using a very plain python, without CodeHilite extension, and I see merely
```
'<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE en-note SYSTEM "http://xml.evernote.com/pub/enml2.dtd">\n<en-note><p>hi</p>\n<p><code>python\nimport os\n</code></p>\n</en-note>'
```
rather than
```
<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE en-note SYSTEM "http://xml.evernote.com/pub/enml2.dtd">\n<en-note><p>hi</p>\n<div class="codehilite"><pre><span></span><code><span class="kn">import</span> <span class="nn">os</span>\n</code></pre></div>\n</en-note>'
class="codehilite"><pre><span></span><code><span class="kn">import</span> <span class="nn">os</span>\n</code></pre></div>\n</en-note>'
```

And the relatively simple content goes through just fine without an error and the note is created.
I use the same input text you suggested, and yet get different HTML.  Not sure why you're getting the more complex HTML.  Any ideas?
