### ISSUE TITLE
Install dependencies

### ISSUE THREAD

**Issue by priezz** [jeffkowalski/geeknote#40]
Hello,

It would be nice it missing dependencies were installed together with geeknote when installing from homebrew. For me it was:
```
pip2 install proxyenv pysqlite
```

P.S. It works sooo slooow :(

**Comment by yantis** [comment]
For the Arch version: https://aur.archlinux.org/packages/geeknote-improved-git/

I added these packages:
https://aur.archlinux.org/packages/python2-proxyenv-git/
https://aur.archlinux.org/packages/python2-htpasswd-git/

**Comment by jeffkowalski** [comment]
I can't see where pysqlite is specifically required, but I just added proxyenv and htpasswd, which were indeed needed.  Re-test?

**Comment by jeffkowalski** [comment]
Should be fully resolved in v2.0.1
