### ISSUE TITLE
Edit a note with raw mode, opened two empty files

### ISSUE THREAD

**Issue by blurm** [jeffkowalski/geeknote#44]
The command I used is ：
`geeknote edit --note "0723" --content "WRITE" --raw`
Two different files opened in vim, one is tmp file without suffix, one's file name is ".org"
If without --raw option, it worked just fine

It looks like note was split based on it's name

**Comment by jeffkowalski** [comment]
confirmed
I use 
```geeknote edit --note "issue44" --content "WRITE" --raw```
to reproduce
