### ISSUE TITLE
Can't edit notes

### ISSUE THREAD

**Issue by emKaroly** [jeffkowalski/geeknote#45]
When i do 
geeknote edit --note "somenotetitle"

This is what happens:

Connecting to Evernote...
Saving Note...
Note Successfuly saved.

**Comment by jeffkowalski** [comment]
That's the expected, perhaps disappointing, behavior.
What you probably want is ```geeknote edit --note "somenotetitle" --content WRITE```
Without one of the arguments to edit, the note will be re-saved unchanged.
Here are the arguments:
```
$ geeknote edit --help                                                            
Options for: edit
Available arguments:
--resource : Add a resource to the note.
 --created : Set local creation time in 'yyyy-mm-dd' or 'yyyy-mm-dd HH:MM' format.
    --note : [default] The name or GUID or ID from the previous search of a note to edit.
--reminder : Set local reminder date and time in 'yyyy-mm-dd' or 'yyyy-mm-dd HH:MM' format.
             Alternatively use TOMORROW and WEEK for 24 hours and a week ahead respectively,
             NONE for a reminder without a time. Use DONE to mark a reminder as completed.
             Use DELETE to remove reminder from a note.
     --tag : Set new tag for the note.
 --content : Set new content of the note.
--notebook : Assign new notebook for the note.
   --title : Set new title of the note.
Available flags:
     --raw : Edit note with raw ENML
```

**Comment by emKaroly** [comment]
The original Geeknote doesn't need that argument right?

**Comment by jeffkowalski** [comment]
Actually, I think it does.  You need to tell it what to edit, the tag, the content, the title,... something.

**Comment by emKaroly** [comment]
I mean i used the original geeknote like this: geeknote edit --note "somenotetitle". without content argument. It opened the note in vim and when i finished it saved the note.

**Comment by jeffkowalski** [comment]
Nonetheless, this version of geeknote requires some "action" to complement the edit, or it will simply re-save the unmodified note.  As above, if you want to mimic the action of the old geeknote, I'd suggest
```geeknote edit --note "somenotetitle" --content WRITE```
See the README for more on editing notes: https://github.com/jeffkowalski/geeknote#notes-editing-notes
