### ISSUE TITLE
can not edit notes

### ISSUE THREAD

**Issue by vitaly-zdanevich** [jeffkowalski/geeknote#47]
version 2.0.3

`geeknote edit <notename>`
trying to open note but after two seconds of animation `>>>` I see `Note successfully saved.`
I tried `geeknote settings --editor vim` without success.

And it is a good idea to add this case to the tests (if now tests do not have such case - I did not run tests).

**Comment by jeffkowalski** [comment]
duplicate of "Can't edit notes #45"
