### ISSUE TITLE
Enable piping of 'find' results without keyboard interaction and without polluting the piped output with extra characters

### ISSUE THREAD

**Issue by paulburton0** [jeffkowalski/geeknote#5]
Currently, there is a 20-note limit for search results, after which a '--More--' prompt appears (if a --count greater than 20 has been used, and of course of there are in fact more than 20 results).

When scripting a 'find', however, the script hangs and waits for a manual "Return" before it will exit. Furthermore, if the output of the search is piped or redirected, the --More-- and control characters are piped along with the results.

I understand Evernote limits the results that can be returned, but is there some other way to buffer them so that they're more friendly to use in automated scripts/cron jobs/etc.?

**Comment by jeffkowalski** [comment]
I'm not seeing the behavior you mention, if I'm understanding you correctly.
In my evernote account, I have many notes tagged "music", and when I use this at the command line:
`geeknote find --tags music --count 100`
I get a long list, uninterrupted by `--More--`, and not pending any further input.

**Comment by paulburton0** [comment]
You are correct. Sorry ... I may still have an instance of the upstream version of geeknote in my path and might have inadvertently used that one ... Nevermind, and thanks for the response!

**Comment by jeffkowalski** [comment]
No worries.  Glad it's working for you.
