### ISSUE TITLE
settings shows `Markdown2 Extras: None` - what is that mean?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [jeffkowalski/geeknote#54]
Can I install some extras for markdown?

**Comment by jeffkowalski** [comment]
Ah, @vitaly-zdanevich, my friend from the other side of earth.  Yes, the documentation has holes and you've found another.  My mission is to turn you from commentator to investigator to contributor ;)

Take a look at the [Python Markdown2 Wiki](https://github.com/trentm/python-markdown2/wiki/Extras) that explains the extras.  I've never tried them.
You can test them by setting them much like you would [your default editor](https://github.com/jeffkowalski/geeknote#setting-up-the-default-editor).
The code to accept settings is in the [argparser](https://github.com/jeffkowalski/geeknote/blob/master/geeknote/argparser.py#L38-L43).
Extras are used in processing markdown text to ENML in the [editor module](https://github.com/jeffkowalski/geeknote/blob/master/geeknote/editor.py#L242)
