### ISSUE TITLE
notebook_path should not be escaped

### ISSUE THREAD

**Issue by rhyc** [jeffkowalski/geeknote#56]
re: commit bbee4b8b99be4128d5ac5b213b783bb557bb795c
geeknote/geeknote/gnsync.py line 489
`escaped_notebook_path = re.sub(os.sep,'-', notebook_path)
os.mkdir(escaped_notebook_path)`

notebook_path is used as a path and should not be escaped.

On a related note, I think escaping notebook and note titles by substituting os.sep with hyphen is problematic, as the program can not distinguish between titles like 'my-title' with 'my/title' afterward.

I suggest raising an exception instead if geeknote finds os.sep in any notebook or note titles.

**Comment by jeffkowalski** [comment]
@rhyc, thanks for reporting.
I've addressed the bug.
As to whether to rewrite the pathnames at all, or raise an exception, I could easily see the case where users might have notes with colons in them, which are forbidden in MacOS, or of course slashes forbidden on Unix.
Maybe the right answer is to add a flag like "--fix-separators", allowing it to proceed, and throwing an exception where we encounter an offending name and the flag was not specified?  In any event, probably best to log the offense as well?
What do you think?

**Comment by jeffkowalski** [comment]
Some other alternatives to control a switch in behavior, either modifying the pathnames or raising an exception:
1. a variable in config.py
2. a setting reachable through ```geeknote settings```
@rhyc, would you like to comment?
