### ISSUE TITLE
Images are removed when editing

### ISSUE THREAD

**Issue by jaguarondi** [jeffkowalski/geeknote#6]
If I insert a picture in evernote, then when I edit the note from geeknote the picture gets removed. This also happens when I include a picture link in my markdown content and then edit the note in evernote. What happens is:
- create markdown note with `![picture](http://some.com/mypic.jpg)`
- this gets translated to `<img alt="picture" src="http://some.com/mypic.jpg"/>` when looking at note.content
- As soon as I edit the note in evernote, even a single character not related to the picture, when reading the note I get this in note.content: `<en-media alt="picture" hash="92256dd5c1173b62086068eb7a0482e1" type="image/jpeg"></en-media>`
It seems evernote embeds the picture in the note somehow.
- Then, the call to `Editor.ENMLtoText(note.content)` just drops the tag and the picture is lost.

Would there be a way to keep this en-media tag intact when editing a note so that the picture stays in place?

**Comment by jaguarondi** [comment]
I made a pull request to fix this. I decided to keep the `<en-media>` tag as html in the markdown document because it's the most convenient to edit it, move it or delete it. And the most important is that it isn't lost anymore.

**Comment by jeffkowalski** [comment]
Closed in 210ad5da79c4c0bf87fade75b954565dc75d09b7, which merges pull request from issue #10.
Thank you @jaguarondi
