### ISSUE TITLE
Repeated requests for authorization

### ISSUE THREAD

**Issue by jwbowers** [jeffkowalski/geeknote#60]
Whether I install geeknote from brew or instructions after cloning the repo, it asks me to authorize Evernote after every command. I am using Two-factor Authentication. Seems like there is a problem in caching my authorization? Any advice appreciated. (Using OS X 10.12.1, brew python, bash shell).

**Comment by jeffkowalski** [comment]
can you tell me what version you're using?
just type ```geeknote``` with no arguments
```
Version: 2.0.7
Geeknote - a command line client for Evernote.
Use geeknote --help to read documentation.
```

**Comment by jwbowers** [comment]
```
aching:~ jwbowers$ geeknote
Version: 2.0.7
Geeknote - a command line client for Evernote.
Use geeknote --help to read documentation.
```

**Comment by lisxray** [comment]
the same issue with me

Regardless of whether two-factor authentication is enabled, it ask me to type 2-F code when I type correct username and password.

And regardless of the code I type, it ends with nothing displayed and all commands still require login.

However,when I type wrong login info, it just shows "Sorry, incorrect login or password"

# geeknote
Version: 2.0.7
Geeknote - a command line client for Evernote.
Use geeknote --help to read documentation.

Could you help me with the issue?

**Comment by arpan-chavda** [comment]
Same issue with me.
Here is error.log file:
2016-11-18 05:26:16,468 oauth allowAccess 288 : Unexpected response status on allowing access 302 != 403

**Comment by jeffkowalski** [comment]
@arpan-chavda thank you for the log file.  That was very helpful.
I've merged in a recent change from pipakin forked from upstream.
Would you mind re-trying now with the head of my 2.0.9 branch, at 2b5f8fc3133eb0bd968fd37f7ab4969752b15a30 ?

**Comment by arpan-chavda** [comment]
Good to go. Though It will ask for TFA for Non-TFA Accounts but User can skip by just pressing enter/empty value. It's working. Thanks for instant work.

**Comment by jeffkowalski** [comment]
@arpan-chavda thank you for the quick re-test and confirmation!
