### ISSUE TITLE
gnsync does not sync existing files

### ISSUE THREAD

**Issue by jezeniel** [jeffkowalski/geeknote#64]
When I try syncing already existing notes it does not sync. This is the log

```
2016-11-21 23:53:26,671 : Sync Start
2016-11-21 23:53:30,898 : 'NoteMetadata' object has no attribute 'tagNames'
2016-11-21 23:53:30,898 : Sync Complete
```

**Comment by jeffkowalski** [comment]
Thanks for the log, @jezeniel 
Would you mind trying the head of 2.0.10, 890b9afe30774763ca97bb74839ff8997d85a720, which I've pulled from @ronin13 ?  It appears to have a different, safer treatment of tagNames.

**Comment by jezeniel** [comment]
@jeffkowalski sorry for the late response. Tested that branch and it works fine now..
