### ISSUE TITLE
--count option to find seems not reliable in some cases?

### ISSUE THREAD

**Issue by gwillen** [jeffkowalski/geeknote#77]
I have a notebook with 800+ notes in it, but when I do "geeknote find --count 999" to see all notes, it returns 749. BUT if I do --count 9999 then it shows all notes. So there's something being counted in the count but filtered out, like deleted notes or something, that is messing with the results count. Can't tell if it's on geeknote's side or evernote's.

**Comment by jeffkowalski** [comment]
Wow, very strange error.  It's not immediately apparent what could be the
cause.
To help in diagnosis, can you find the breaking point where the # requested
!= # returned?
Is it 250?  249?  251?
Maybe binary search can help determine that breaking point.
Thanks.

**Comment by gwillen** [comment]
Hm it's very interesting actually. Number requested versus number received (out of 864 total; I didn't probe every possible number but assumed monotonicity):

- 0-500 -> correct number (0-500)
- 500-750 -> stuck at 500
- 751-1000 -> correct number minus 250 (501-750)
- 1001-1500 -> stuck at 750
- 1501-1614 -> correct number minus 750 (751-864)

Then I run out of items to test on.

So ... some kind of pagination bug, I think? Thanks for looking into this!

**Comment by gwillen** [comment]
Yes, it must be a bug in the handling of Evernote find count limits, because that limit appears to be 250.

**Comment by jeffkowalski** [comment]
That's helpful.
There is indeed a limit on the length of the result array from the Evernote
findNotesMetadata API.  According to the docs (
https://dev.evernote.com/doc/reference/NoteStore.html#Fn_NoteStore_findNotesMetadata),
it won't return more than 250 per call.
You can see the code that's supposed to walk along all the results, setting
an offset in each successive call until the desired count is achieved.
The code is at line 247 in geeknote/geeknote.py, midway through the
findNotes function.
It's not apparent to me what might be going wrong - perhaps your eyes are
better than mine.  I wouldn't rule out a simple logic or math error.
