### ISSUE TITLE
Geeknote is very very verbose on saving a note

### ISSUE THREAD

**Issue by jmburges** [jeffkowalski/geeknote#87]
Hello!

When I run `geeknote edit 1` and it then opens my note in mvim, whenever I hit save I get this super verbose message in my terminal

```
Note(contentHash='\x0bh\x91\xdf\xb5\xdbr^\xeb\x85\x8a\xe1\x89\x00\xbf\x17', updated=1489612672000, created=1476294932000, deleted=N
one, contentLength=1710, title='MYTITLE', notebookGuid='e2c6a1b4-4163-4407-8efb-8082e9d70172', notebookName='Inbox',
content='<HTMLTAGS CONTAINING MY CONTENT>', tagNames=None, updateSequenceNum=16255, tagGuids=None, 
active=True, attributes=NoteAttributes(lastEditorId=None, placeName=None, sourceURL=None, classifications=None, creatorId=None, author='NAME
 ', reminderTime=None, altitude=10.158684730529785, reminderOrder=None, shareDate=None, reminderDoneTime=None, longitude=XXXXXXX
1596694, lastEditedBy=None, source='desktop.mac', applicationData=None, sourceApplication=None, latitude=XXXX, contentClass=No
ne, subjectDate=None), guid='f9669af9-0ad0-4da5-9461-bd92b9042a64', resources=None)
```

Any ideas on how I can turn that off. In vim in fact it loads into the vim window, corrupting the window

**Comment by jeffkowalski** [comment]
Which version of geeknote are you using (just type geeknote with no
arguments and it will tell you) ?  Do you have DEBUG or DEV_MODE set in
config.py?

**Comment by jmburges** [comment]
Such a fast response! thank you.

I checked my config.py and both DEBUG and DEV_MODE are set to `False`. I'm running Version: 2.0.11. 

Any ideas of where I should look?

**Comment by jmburges** [comment]
Ok so I have reinstalled everything and it's still happening. I looked through the geeknote source code and I don't think it's coming from there. Maybe it's coming from the Evernote pip package?

**Comment by jeffkowalski** [comment]
Please describe how you have installed geeknote.
Also, can you describe where the geeknote files can be found across your system?

**Comment by jlmcgehee21** [comment]
I was experiencing this in `neovim` on version `2.0.16` -- I updated to `2.0.20` and it seems to be resolved.

**Comment by jlmcgehee21** [comment]
Just went looking through the release history, and it appears this PR addressed this issue: https://github.com/jeffkowalski/geeknote/pull/105

**Comment by jeffkowalski** [comment]
Thank you for confirming that it's fixed, @jlmcgehee21 !
