### ISSUE TITLE
Problem with login

### ISSUE THREAD

**Issue by elig0n** [jeffkowalski/geeknote#90]
https://i.imgur.com/iJaZ43C.gifv

I'm using WSL.

**Comment by b-ryan** [comment]
I'm getting the same thing. Logs just show:

```
2018-04-16 12:46:54,465 oauth getTmpOAuthToken 202 : Unexpected response status on get temporary oauth_token 200 != 401
```

**Comment by atwinkelman** [comment]
I'm getting the same error in the log. I'd be willing to bet it's related to #89.

**Comment by b-ryan** [comment]
Thanks @atwinkelman - that certainly makes sense.
