### ISSUE TITLE
Couldn't login

### ISSUE THREAD

**Issue by saamkhya** [jeffkowalski/geeknote#95]
Has Evernote granted permission to the geeknote after they closed it? Is this still active? 
I was able to install but unable to login, geeknote login is returning following message:
OAuth token request failed              
If you have an Evernote developer token, enter it here:

**Comment by tuanlc** [comment]
Faced with the same problem.

**Comment by saamkhya** [comment]
Fixed the problem. Just ask the evernote support team to issue you the developer token. For more info, read the thread: https://github.com/jeffkowalski/geeknote/issues/89
